import Sidebar from "./Sidebar";

function Content() {
  return (
    <div aria-label="Content" className="bg-neutral-200 p-4 h-screen flex justify-center dark:bg-slate-600 dark:text-neutral-200">
      <Sidebar />
      <div className="bg-slate-300 mx-4 p-8 text-center overflow-y-scroll dark:bg-slate-700" >
      <h2 id="login" >LOGIN</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci neque quidem odio aut fuga unde alias consectetur dicta ut nulla dolor similique cupiditate vitae quod esse blanditiis fugiat, deserunt illum.
      Ipsum eveniet quidem veritatis esse non maiores, deleniti reprehenderit facere ad similique provident quaerat perferendis magnam cumque dicta. Vitae ipsam molestias fugit, doloribus expedita fugiat tenetur consequuntur iure nesciunt unde.
      Eligendi, itaque sint alias aliquam aperiam minima dolorem tenetur facilis tempore explicabo minus? Dicta ab, velit, esse ipsam expedita debitis quae asperiores alias optio a tenetur, labore quam reprehenderit. Fugit?
      Tenetur sequi veniam quaerat molestias? Voluptatibus vitae ad adipisci. Culpa numquam, esse quas dolores iste ab quisquam, beatae voluptatem placeat minus iure! Cum, ipsam. Optio hic accusantium officia quam eius?
      Accusamus nisi possimus non quaerat inventore, quae sunt necessitatibus magni perferendis at neque dolorum aliquam, dicta, rem asperiores omnis nesciunt maxime iure quo veritatis voluptatem quam ad commodi corporis? Eligendi?
      Dolorem quibusdam quasi laboriosam distinctio quae aspernatur, quisquam dolore consequatur sapiente esse assumenda reprehenderit sint numquam cupiditate nesciunt sequi. Vitae quibusdam, nostrum dolores eaque nemo sapiente deleniti odio est excepturi?
      Iste sequi repudiandae quae aperiam quibusdam iure, non officiis commodi aliquam consequuntur autem sint. Fugiat dicta veniam porro expedita et officia, debitis ipsam pariatur, eos nobis suscipit. Nisi, eveniet sapiente!
      Autem iusto, a cumque rem totam amet obcaecati quidem molestias incidunt ipsa quas placeat corrupti accusamus et quibusdam? Cupiditate illum neque nam a sit quisquam consectetur sint exercitationem enim magni.
      Deleniti ratione totam nobis officiis veniam unde dignissimos doloribus non rerum, consequuntur aspernatur illo ullam error illum sequi voluptas. Tenetur eaque, beatae facere odio provident ipsa exercitationem debitis quia unde?
      Corporis deleniti nesciunt voluptatibus necessitatibus non consequatur sint tempora ipsum, minima itaque at expedita tempore iusto dolorem maxime possimus repellendus aliquid. Eos voluptates facilis provident ad! Nemo provident asperiores sed?
      Nesciunt deserunt, ipsam rerum deleniti delectus sequi tempore. Autem, magnam! Sed a soluta saepe eum ex eveniet culpa doloremque harum officia nam laborum laboriosam dignissimos earum odio quia, ea voluptates!
      Reiciendis quidem fuga vel ipsa incidunt nostrum nemo blanditiis sit delectus quos voluptatum, sapiente error dicta itaque ipsam omnis quaerat, neque optio? Mollitia pariatur officiis ipsum maxime ratione cum aspernatur.
      Minima officia consectetur unde dolorem expedita optio ipsa accusantium quas esse. Provident exercitationem dolorem esse cumque corporis necessitatibus odit pariatur? Commodi doloribus beatae aspernatur iusto nulla, fugit explicabo similique ipsum!
      Adipisci, harum consectetur ea dolore voluptas veritatis dignissimos, nostrum et, voluptates veniam quidem ducimus odit minima natus aut sapiente! Similique reiciendis possimus quod voluptate inventore, non dignissimos ut vero odio!
      Doloribus mollitia quisquam, sequi aperiam rem aspernatur quam minima officiis vel odio iusto, at quibusdam. Sint eum, harum cupiditate totam quaerat nobis dolore, fugiat, iste consectetur dicta dolorem ipsam. Vero?
      Corrupti nihil asperiores sed minima quaerat vero necessitatibus ullam aut iure? Omnis asperiores vero sit dolore animi aut laborum repellendus rerum, a mollitia minus. Beatae aliquam assumenda hic eos architecto.
      Dolores laudantium amet pariatur perferendis saepe soluta facere magnam sit dolorem totam architecto vero magni omnis iusto, reprehenderit earum fuga illum corporis voluptatibus. Ut doloremque, beatae odio quaerat voluptas quidem.
      Rerum officiis necessitatibus, quis facere delectus possimus vitae sint. Necessitatibus, blanditiis laudantium? Soluta earum alias consectetur totam! Eos placeat ex soluta assumenda atque ipsam vero aut, libero delectus quaerat magnam.
      Ea accusantium nulla, quod tenetur laborum optio dignissimos laudantium, molestiae doloribus quo at quos beatae odit necessitatibus. Exercitationem eius molestias nobis commodi? Quo facilis ut nisi magni tempore harum laboriosam.
      Similique, facere. Vero facere voluptatem obcaecati excepturi iure, eos praesentium soluta eligendi ut! Odit, blanditiis, similique possimus sint unde expedita, excepturi magni ratione natus magnam vitae ullam animi libero necessitatibus.
      Recusandae nisi numquam tempore. Quam cum laborum at mollitia error. Voluptatem, non qui quae ullam consequatur quas aut voluptates expedita. Fugiat vero impedit voluptas, harum iste necessitatibus quisquam perferendis ex!
      Facere reiciendis nostrum, necessitatibus quae autem tenetur, sed reprehenderit distinctio et adipisci at sint in? Autem beatae iure distinctio delectus. Aliquid animi, beatae aut blanditiis tempora minus earum nihil illum!
      Animi reprehenderit enim deleniti quis consectetur eum tempore ipsum facere, praesentium modi possimus aliquam laboriosam, eaque blanditiis vitae pariatur eligendi. Odit saepe iusto odio nemo, impedit quaerat quos dicta reprehenderit.
      Fugiat magnam, nihil eaque sequi illo explicabo sunt neque incidunt. Facilis consectetur, non necessitatibus quas fugit, dolorem ipsum sed dolor est nesciunt modi dolore. Iusto libero at voluptatibus aliquam officia.
      Nesciunt perspiciatis, corporis aliquid, est nostrum necessitatibus recusandae, qui in quas consequuntur hic explicabo consectetur! A aliquid pariatur sed ex. Nesciunt non repellat in. Quam iste optio fuga in quas!
      Impedit magni atque laboriosam, aliquid inventore rem, ad ratione pariatur assumenda quisquam earum debitis libero, ex molestias vel sint sit? Facere itaque iusto est libero? Rerum error deleniti aliquam possimus!
      Molestiae quod minima voluptates saepe, quis ut nobis, debitis fugiat accusantium minus, ipsam nostrum laborum atque numquam praesentium dignissimos quisquam facere eos nam placeat exercitationem perspiciatis? Molestiae libero quia vitae.
      Facilis minima architecto vitae rem sunt repudiandae facere molestiae, dolore asperiores quas maxime maiores aut molestias nostrum tempore, doloremque cupiditate tempora corporis autem similique nihil eius et quo. Quis, fugiat?
      Voluptates enim est nobis et architecto incidunt iure aut placeat iste ad ducimus quasi magni dolorum optio veniam dicta nemo rerum alias, assumenda soluta, ea aperiam natus. Consequatur, at quia.
      Qui, eaque ratione dolor hic praesentium consequatur, molestias magnam incidunt sed cumque possimus quasi delectus aliquam, placeat itaque alias cum. Sit exercitationem natus et nobis laboriosam earum minus aliquid excepturi!
      Error, dolore a obcaecati perspiciatis excepturi alias corporis fugiat corrupti vel amet! Libero rerum quas, consequatur nesciunt corporis, odio fugit neque id delectus ipsa mollitia consequuntur beatae fuga ab aperiam?
      Tenetur vero officia impedit quo error neque! Eveniet voluptate magnam, earum repudiandae deleniti dolorem, incidunt suscipit ut sapiente at nihil optio perferendis id vel pariatur sequi, molestias exercitationem maxime enim.
      Numquam tenetur consequatur expedita odit. Minima quod laudantium labore error ab temporibus nesciunt architecto aliquid, quaerat ratione alias. Esse dolore itaque, corrupti accusamus facilis iure cupiditate similique tempore iusto ipsam?
      Exercitationem maiores tenetur nisi non magni quod officia fugit dolore nihil! Voluptate atque ex aspernatur? Reiciendis dolor explicabo et dolores eos veniam amet tenetur corrupti, ad ea atque. Repudiandae, porro!
      Cupiditate distinctio dolore illum laborum itaque facere quaerat, unde voluptates omnis sunt rerum quasi officia eligendi incidunt doloremque qui delectus. Reiciendis laboriosam excepturi nisi repellat ipsam quasi ullam totam aliquam?
      Ullam, minus corporis amet eum maxime ratione recusandae? Voluptate saepe doloremque architecto quod totam commodi ut error provident sunt incidunt dolore excepturi sint, exercitationem tempora maxime culpa amet, voluptatem obcaecati?
      Repellat consectetur neque vel quidem perferendis mollitia quos vero sunt pariatur nemo voluptates, ullam reprehenderit reiciendis aperiam odit a aut accusantium, autem animi corrupti qui? Cumque facere repudiandae doloremque voluptatum.
      Neque placeat repellendus totam mollitia iusto. Quam vel exercitationem modi obcaecati, nobis placeat eos deserunt doloribus laboriosam maxime dicta dolorem nisi reiciendis, illum id repellendus aspernatur facere sequi! Debitis, similique?
      Est amet quam officiis. Minus quibusdam ducimus culpa id ut laborum asperiores dicta amet. Sunt iusto quis adipisci sint ut hic quo aut, neque blanditiis sequi harum quam. Veritatis, harum!
      Nisi velit quisquam, consequuntur maxime quidem ut exercitationem odio vitae necessitatibus accusamus, incidunt nemo! Distinctio iste ex vitae nemo labore animi vero asperiores officia. Voluptate reprehenderit repudiandae consequatur dolorum praesentium.
      Harum incidunt minus quos nesciunt animi accusamus. In nesciunt, iste laboriosam dicta, voluptatibus repudiandae, sapiente aut assumenda reprehenderit veritatis totam. Porro eaque cupiditate at, illo obcaecati delectus culpa cumque et.
      Delectus assumenda accusantium libero praesentium, nulla deleniti fugiat repellat voluptates velit in sapiente eos veniam odio a exercitationem? Quasi dicta eum illum tenetur aliquam ad voluptates veniam fugiat neque saepe?
      Eligendi soluta, itaque beatae quia facere eum perferendis ut nobis molestiae esse culpa eos modi fugiat qui ea sit similique delectus. Culpa veniam reprehenderit commodi obcaecati est corporis minima doloremque?
      Totam dolorem illum nostrum magni fugit voluptates aliquid sint modi! Earum nemo ab alias eos odio repellat repellendus consequuntur, expedita officiis veniam, dignissimos at placeat! Quo, eum. Omnis, veritatis sit.
      Velit hic temporibus perspiciatis expedita quisquam consectetur nam voluptas non quas odio recusandae aut rem ipsum eum quis quidem repudiandae incidunt impedit consequatur officia ipsa est, nihil ad. Neque, labore.
      Sed obcaecati laborum, error quidem cumque minima. Ducimus eveniet, mollitia consequuntur reiciendis libero tempore quod est! Cupiditate reiciendis temporibus sed itaque minus voluptates eos tempore alias dicta, expedita, perferendis ullam.
      Voluptatum aspernatur cum, odit qui fugiat mollitia architecto quos temporibus incidunt ipsam rem in! Beatae qui reiciendis enim rem quos itaque ea voluptates error? Ullam sint vero porro ad consequuntur!
      Praesentium earum consectetur quasi saepe id possimus maiores beatae, incidunt sit totam quisquam voluptas officia corporis mollitia vel architecto impedit libero? Nobis, mollitia laborum? Expedita laudantium beatae nam iure accusantium.
      Dignissimos ipsa repellat quisquam accusamus, nostrum dolor quo officia iste consectetur reprehenderit illo ab? Distinctio nulla neque sapiente quam eligendi, cum omnis earum voluptates natus culpa, sunt at quas beatae.
      Quia a commodi, eligendi deserunt suscipit error ullam dolores qui in totam, sunt magni delectus laborum consectetur dicta explicabo, iusto porro nulla quae. Fugiat laborum architecto iure minima id perspiciatis?
      Ullam ratione neque ut debitis voluptatibus reprehenderit voluptatum, dolore tempora! Esse, cumque architecto doloremque, eum quia neque nisi accusamus modi soluta voluptatibus dignissimos quo suscipit cupiditate placeat! Accusamus, at eligendi!
      Impedit perferendis dignissimos aut voluptates labore, accusantium cumque praesentium distinctio pariatur ad? Aliquid, maiores? Ipsum vel illum veritatis dolorum amet, voluptatem quo qui sit illo accusamus tempore ab possimus debitis!
      Consectetur, nostrum vitae harum ab architecto possimus quam officia quod minus delectus voluptatem itaque aliquid libero aspernatur adipisci mollitia molestias at? Dolor exercitationem sit blanditiis quidem debitis maxime reiciendis dolores.
      Veritatis minima voluptas similique ea, quis quos enim animi rerum vitae sunt odit ex veniam nisi officiis optio, adipisci corrupti quod, earum debitis aut! Distinctio consequuntur porro quas laborum odit.
      Corrupti ipsa, sit totam nisi iusto deleniti officiis cumque commodi impedit amet tempore, ad animi esse dicta nihil placeat molestiae quos doloribus consectetur dolorum minima. Sapiente corrupti magni cupiditate dicta?
      Et incidunt minus, dolor rerum nihil consequatur soluta repudiandae eius autem beatae sunt tempora repellat praesentium. Voluptatibus eaque quos id natus, sit deserunt quas ducimus odit, architecto iste consequuntur itaque?
      Modi iusto similique, vero pariatur labore temporibus recusandae veniam incidunt quis non! Laudantium fuga doloribus corrupti sequi tempore assumenda laborum vel quibusdam excepturi earum! Accusamus qui amet dolor animi fuga.
      Consequuntur, at explicabo facere iusto odio natus? Praesentium qui dolor hic obcaecati adipisci nulla veniam placeat quia similique, quibusdam amet, expedita inventore recusandae nostrum vel iure! Praesentium ea aspernatur sapiente.
      Facere amet soluta fugit accusamus error consequatur nostrum aliquid? Suscipit atque earum commodi. Dignissimos sint ut consequuntur sapiente est veritatis nihil rem repellendus voluptas libero, deserunt ipsum. Cum, obcaecati animi.
      Accusantium maxime natus voluptate ipsa doloribus quo laborum eveniet vel nesciunt possimus similique, facere fuga adipisci! Ab deleniti error qui nihil veritatis, dolor porro id asperiores quae, ducimus necessitatibus consectetur!
      Ullam possimus reprehenderit corporis itaque nulla hic explicabo quae nisi quod nihil, id distinctio quisquam. Quas eveniet, id possimus placeat odio minus saepe repellat soluta, magnam, fuga reprehenderit illum nihil.
      Ut porro rem enim officia! Incidunt atque cupiditate expedita porro deserunt placeat accusamus at delectus. Consequuntur quod est impedit error dolores sequi reiciendis illum voluptatibus, sunt atque rerum. Cumque, impedit?
      Maxime vero autem corporis ad. Eius adipisci debitis temporibus? Dignissimos placeat dolore incidunt in cupiditate id, blanditiis voluptates asperiores cum necessitatibus distinctio nisi, nobis quasi ex mollitia delectus tempora exercitationem.
      Repellat iure suscipit aliquam adipisci eaque corporis, dolorem delectus nesciunt ipsam labore provident sit accusantium placeat officia obcaecati, maxime est enim quis libero tempora voluptate. Quis dolores totam molestias magnam.
      Blanditiis, rerum. Natus odit necessitatibus quod beatae maxime molestiae obcaecati dicta recusandae sed impedit possimus delectus ut quisquam qui at quia aperiam, eveniet minus perspiciatis aspernatur. Impedit unde itaque quae?
      Ipsum in quaerat ea nulla quasi incidunt, quo, enim nostrum unde reiciendis libero recusandae. Necessitatibus veniam dolore consequuntur beatae. Quia nulla corrupti illum eveniet odio incidunt, similique at rem amet!
      Tenetur praesentium voluptate culpa minima maiores omnis ea numquam nam in atque deleniti consectetur voluptatibus neque iste nemo, voluptatum cupiditate harum veniam velit nihil recusandae. Ut unde iusto quasi asperiores?
      Enim dolorem aliquid maxime suscipit, eveniet, quisquam alias exercitationem, illum molestiae provident ad consectetur? Beatae soluta quo explicabo vitae eaque corporis cum illo. Dolorem suscipit numquam laborum eligendi at adipisci.
      Dolorem voluptatibus soluta quas autem exercitationem inventore rerum quaerat molestiae distinctio iusto assumenda error sit, officiis reiciendis tempora ullam iure. Molestiae, laborum! Commodi voluptate delectus, quibusdam architecto voluptatum possimus magni.
      Harum, soluta dolorem libero provident sapiente velit quos nesciunt, temporibus, odit obcaecati amet ducimus consequuntur ipsam dolores qui! Est delectus sequi maxime placeat sit earum, maiores dignissimos officia dolore quo.
      Delectus cupiditate earum praesentium odio officiis quae architecto corrupti dolorem. Dignissimos eum distinctio numquam nisi iure, repudiandae placeat. Aliquid amet corporis vero dicta sint neque culpa deleniti non fugit porro.
      Laboriosam repellat eius aperiam sit quod fugit sed placeat corporis magni veniam magnam quae odit aliquam vel sunt odio fuga natus, maxime culpa officia nesciunt assumenda voluptatibus corrupti. Saepe, minus.
      Est vel deleniti sunt nulla at. Est saepe at nemo neque quidem delectus, facilis necessitatibus nesciunt, rem mollitia itaque deleniti aspernatur quam iure reprehenderit id veritatis hic ea aliquam! Illo.
      Excepturi quam, voluptates provident asperiores voluptas ad cupiditate dolore non commodi recusandae soluta? Voluptates ipsam beatae magnam deleniti, deserunt facere quam tenetur laborum dolore accusamus vitae nobis fuga perferendis molestiae?
      Cupiditate eveniet impedit cum dicta rerum. Error ad fuga distinctio minima blanditiis quasi magnam obcaecati ullam necessitatibus voluptate ab, ipsum possimus ut sunt esse impedit! Aliquam reprehenderit recusandae rem aperiam?
      Provident omnis autem non esse laboriosam, ipsum, unde architecto, quos fugiat aliquid rem corporis illo? Eum deleniti eaque similique blanditiis reiciendis? Unde sequi necessitatibus modi in molestias facilis assumenda perferendis.
      Nihil at repudiandae aspernatur facilis! Quisquam iusto veritatis, natus itaque provident distinctio fugit recusandae quas quibusdam eos, dignissimos pariatur, mollitia obcaecati repellat placeat. Iure, illum repellendus! Quia quod nihil placeat?
      Fuga quas nulla suscipit tenetur quidem provident non illum doloribus, ad placeat vel animi fugit alias deleniti doloremque aliquam optio impedit dolor! Sed delectus amet incidunt aperiam est reprehenderit vel.
      Ea ullam iste ipsa sapiente tempora nobis sit voluptate! Velit, in. Eveniet voluptatibus maiores placeat, deserunt officia officiis? Vitae pariatur voluptatem ipsa cupiditate omnis expedita facere esse autem ut libero!
      Tempore, incidunt accusamus quasi maiores vero dicta provident neque qui ullam blanditiis reiciendis quod minus in esse consequatur quaerat necessitatibus! Maxime, consectetur dolor non exercitationem totam alias ad aliquid praesentium.
      Consequuntur id accusamus dolorum dicta aliquam consequatur aperiam atque, dolor beatae vero earum amet voluptate facere temporibus doloribus ea molestiae aspernatur ipsam a corrupti vitae odit. Eum, perferendis laborum. Deserunt.
      Suscipit neque dolore tempore, itaque fugit odio non quis quibusdam laborum sed, alias perspiciatis. Minus adipisci reprehenderit placeat dolores ducimus corrupti mollitia consequuntur exercitationem labore earum. Non deserunt obcaecati ab!
      Voluptatem similique cumque deserunt dolorem mollitia veniam, rem ipsa error repellendus doloribus nesciunt ratione laborum repudiandae id nisi sed maiores officia, excepturi recusandae aliquam? Rerum est magni quaerat optio in!
      Mollitia, alias dolores excepturi libero voluptas fugiat sapiente, officiis soluta, inventore eaque ad dolor. Excepturi ducimus, hic, ea repellat dolor veritatis eligendi cupiditate magnam minus beatae consequuntur assumenda adipisci ad!
      Officia quis aliquam modi tenetur eum! Sint nulla voluptatum in veniam autem itaque cum fugit unde adipisci accusamus, libero fugiat enim iste, beatae blanditiis doloremque! Libero, maiores aut. Modi, dolor.
      Error rerum fugiat repudiandae autem, consectetur sed! Illo beatae sapiente fuga accusantium, sit, optio at commodi, doloribus voluptatibus quam impedit temporibus debitis? Ea consectetur, doloremque quisquam fuga libero culpa assumenda.
      Voluptatum, qui neque facilis libero doloribus porro ipsum corrupti nemo unde vitae dolor officiis ad exercitationem quos reprehenderit alias ratione quam voluptate quo nam quidem! A dignissimos excepturi explicabo recusandae.
      Porro tenetur vel, eos neque corporis autem natus facilis consequatur provident magnam molestiae quibusdam accusantium ad repudiandae ipsam, voluptatem distinctio vero in. Et tempora repudiandae voluptates ducimus ad sapiente deserunt.
      Qui exercitationem sunt error quibusdam, dolorem consequatur obcaecati illo iure ab odio molestiae tempore saepe fugiat enim ipsa laboriosam. Saepe quisquam suscipit enim, repudiandae voluptatibus molestiae magnam nihil ab! Animi!
      Dolore odio minima autem perspiciatis reiciendis, amet quia veritatis aperiam obcaecati assumenda officiis delectus optio. Enim consequatur earum autem, eius tenetur consectetur delectus saepe, culpa possimus sed aliquid expedita velit.
      Omnis nemo nesciunt, veniam accusamus at quo voluptatibus laboriosam animi earum sint soluta dolore tenetur, cupiditate quasi quos sunt est iste autem, mollitia quaerat necessitatibus! Architecto ad dolor unde rerum!
      Suscipit eius placeat, atque eum, ratione, veritatis porro est cupiditate culpa deserunt laboriosam. Nisi est quod facilis similique non, ad eius vero asperiores. Itaque, voluptate pariatur. Adipisci delectus eveniet tempora?
      Sequi tempora, sapiente ratione corporis eius ipsa voluptatem, architecto optio, inventore eum beatae aspernatur cum pariatur provident voluptatibus fugiat error! Perferendis tenetur expedita sint quaerat possimus nisi voluptatum dolores non.
      Modi culpa suscipit impedit fuga cum blanditiis molestiae aut facilis pariatur earum, distinctio autem deleniti alias eius accusamus itaque excepturi molestias nostrum ullam? Sint eius culpa quidem consequuntur necessitatibus impedit.
      Architecto temporibus totam consectetur voluptatibus iste explicabo! Exercitationem quasi culpa blanditiis ipsam libero velit laudantium atque voluptas non optio natus consectetur adipisci quaerat voluptate temporibus, similique voluptates repudiandae delectus facere.
      Dolorem earum placeat delectus exercitationem consequuntur eligendi totam pariatur sequi ipsa in aliquid quod ab ad, veritatis, officia aspernatur hic quos vitae. Fugiat deleniti dolore eum natus voluptatibus ullam atque!
      Iste eos dolorem quaerat veniam unde beatae repudiandae, excepturi mollitia vero! Ipsa facere ut et, corrupti magni assumenda, itaque vitae animi reiciendis quibusdam voluptatem inventore, dolor consequuntur nobis vero rerum?
      Quaerat fugit doloribus maiores sequi perspiciatis explicabo beatae aliquid deserunt minus harum deleniti, cum error illo eaque quidem, dolor nisi quo similique illum vero repudiandae facere sed. Eligendi, consequatur libero!
      Deserunt pariatur totam sit. Quaerat, veritatis in sed maxime sequi nobis impedit officia itaque reiciendis dolorem voluptate dolor, ratione inventore iure rem accusantium! Nam recusandae expedita corporis omnis iusto minima?
      Voluptatem, consectetur porro. Quos quasi at corrupti necessitatibus officiis esse cupiditate dolores? Atque velit sequi deserunt quod laudantium tempora. Nesciunt optio corporis eveniet maiores similique, facere at ea iste eum.</p>
      <h2 id="prueba" >prueba</h2>
      </div>
    </div>
  );
}

export default Content;
